//! Combined module Auto-generated by Narayan Refactor

pub mod memory_store {
use async_trait::async_trait;

use crate::tools::{ParameterSchema, Tool, ToolResult, schema_string, schema_boolean};
pub struct MemoryStoreTool;
#[async_trait]
impl Tool for MemoryStoreTool {
    fn name(&self) -> &str {
        "memory_store"
    }
    fn description(&self) -> &str {
        "Store a key-value pair in the agent's memory for later recall across steps."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::required("key", "string", "Memory key."),
            ParameterSchema::required("value", "string", "Value to store."),
            ParameterSchema::optional("agent_id", "string", "Agent ID scope (default: 'global')."),
        ]
    }

    fn output_schema(&self) -> Option<serde_json::Value> {
        Some(serde_json::json!({
            "type": "object",
            "required": ["stored", "key", "scope"],
            "properties": {
                "stored": schema_boolean(),
                "key": schema_string(),
                "scope": schema_string(),
            },
            "additionalProperties": true,
        }))
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        let key = match args["key"].as_str() {
            Some(k) => k,
            None => return Ok(ToolResult::err("'key' required")),
        };
        let value = match args["value"].as_str() {
            Some(v) => v,
            None => return Ok(ToolResult::err("'value' required")),
        };
        let scope = args["agent_id"].as_str().unwrap_or("global");
        crate::tools::memory_store_internal::insert(format!("{scope}:{key}"), value.to_string());
        Ok(ToolResult::ok(serde_json::json!({"stored": true, "key": key, "scope": scope})))
    }
}

}
pub mod memory_recall {
use async_trait::async_trait;

use crate::tools::{ParameterSchema, Tool, ToolResult, schema_string, schema_boolean};
pub struct MemoryRecallTool;
#[async_trait]
impl Tool for MemoryRecallTool {
    fn name(&self) -> &str {
        "memory_recall"
    }
    fn description(&self) -> &str {
        "Retrieve a stored value from agent memory by key."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::required("key", "string", "Memory key to retrieve."),
            ParameterSchema::optional("agent_id", "string", "Agent ID scope (default: 'global')."),
        ]
    }
    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        let key = match args["key"].as_str() {
            Some(k) => k,
            None => return Ok(ToolResult::err("'key' required")),
        };
        let scope = args["agent_id"].as_str().unwrap_or("global");
        let value = crate::tools::memory_store_internal::get(&format!("{scope}:{key}"));
        Ok(ToolResult::ok(serde_json::json!({"key": key, "value": value, "found": value.is_some()})))
    }
}

}
pub mod memory_forget {
use async_trait::async_trait;

use crate::tools::{ParameterSchema, Tool, ToolResult, schema_string, schema_boolean};
pub struct MemoryForgetTool;
#[async_trait]
impl Tool for MemoryForgetTool {
    fn name(&self) -> &str {
        "memory_forget"
    }
    fn description(&self) -> &str {
        "Delete a key from agent memory."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::required("key", "string", "Memory key to delete."),
            ParameterSchema::optional("agent_id", "string", "Agent ID scope (default: 'global')."),
        ]
    }
    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        let key = match args["key"].as_str() {
            Some(k) => k,
            None => return Ok(ToolResult::err("'key' required")),
        };
        let scope = args["agent_id"].as_str().unwrap_or("global");
        let removed = crate::tools::memory_store_internal::remove(&format!("{scope}:{key}"));
        Ok(ToolResult::ok(serde_json::json!({"deleted": removed, "key": key})))
    }
}

}
pub mod memory_consolidate {
use std::sync::Arc;

use async_trait::async_trait;

use crate::{
    memory::{apply_consolidation_metadata, MemoryConsolidator},
    storage::PostgresStore,
    tools::{ParameterSchema, Tool, ToolResult},
};

#[derive(Clone)]
pub struct MemoryConsolidateTool {
    store: Arc<PostgresStore>,
    consolidator: Arc<MemoryConsolidator>,
}

impl MemoryConsolidateTool {
    pub fn new(store: Arc<PostgresStore>, consolidator: Arc<MemoryConsolidator>) -> Self {
        Self { store, consolidator }
    }
}

#[async_trait]
impl Tool for MemoryConsolidateTool {
    fn name(&self) -> &str {
        "memory_consolidate"
    }

    fn description(&self) -> &str {
        "Run a durable memory consolidation pass for a successfully completed agent. This merges recent successful signal into topic memories, updates the memory index, and prunes stale topics."
    }

    fn category(&self) -> &'static str {
        "memory"
    }

    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::required("tenant_id", "string", "Tenant ID injected automatically."),
            ParameterSchema::required("agent_id", "string", "Agent ID injected automatically."),
            ParameterSchema::optional(
                "force",
                "boolean",
                "Bypass the no-new-signal gate while still requiring a completed successful run.",
            ),
        ]
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        let tenant_id = match args.get("tenant_id").and_then(|value| value.as_str()) {
            Some(value) if !value.trim().is_empty() => value,
            _ => return Ok(ToolResult::err("'tenant_id' is required")),
        };
        let agent_id = match args.get("agent_id").and_then(|value| value.as_str()) {
            Some(value) if !value.trim().is_empty() => value,
            _ => return Ok(ToolResult::err("'agent_id' is required")),
        };
        let force = args.get("force").and_then(|value| value.as_bool()).unwrap_or(false);

        let Some(mut state) = self.store.get_agent(tenant_id, agent_id).await? else {
            return Ok(ToolResult::err(format!("agent '{}' was not found", agent_id)));
        };

        let result = self.consolidator.consolidate_agent(&state, force).await?;
        if !result.skipped {
            apply_consolidation_metadata(&mut state, &result);
            self.store.upsert_agent(&state).await?;
        }

        Ok(ToolResult::ok(serde_json::json!({
            "changed": result.changed,
            "skipped": result.skipped,
            "summary": result.summary,
            "topics_saved": result.topics_saved,
            "pruned_topics": result.pruned_topics,
            "topic_keys": result.topic_keys,
            "index_key": result.index_key,
        })))
    }
}

}

// Re-exports
pub use memory_store::MemoryStoreTool;
pub use memory_recall::MemoryRecallTool;
pub use memory_forget::MemoryForgetTool;
pub use memory_consolidate::MemoryConsolidateTool;
