//! Combined module Auto-generated by Narayan Refactor

pub mod vector_store {
//! vector_store — Embed text and store it in pgvector semantic memory.
//!
//! Agents use this to persist knowledge across steps and across runs.
//! Stored documents are retrievable via vector_search using semantic similarity.

use std::sync::Arc;

use async_trait::async_trait;

use crate::{
    memory::{EmbeddingModel, PgVectorStore, VectorDocument, VectorStore},
    tools::{ParameterSchema, Tool, ToolResult},
};

pub struct VectorStoreTool {
    pub store: Arc<PgVectorStore>,
    pub embedder: Arc<dyn EmbeddingModel>,
}

#[async_trait]
impl Tool for VectorStoreTool {
    fn name(&self) -> &str {
        "vector_store"
    }
    fn description(&self) -> &str {
        "Embed text and store it in the agent's semantic memory (pgvector). \
         Content is retrievable later via vector_search using natural language queries. \
         Use for facts, findings, summaries, code snippets — anything worth remembering."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::required("content", "string", "Text content to embed and store."),
            ParameterSchema::required("agent_id", "string", "Agent ID — injected automatically."),
            ParameterSchema::required("tenant_id", "string", "Tenant ID — injected automatically."),
            ParameterSchema::optional(
                "doc_id",
                "string",
                "Explicit document ID (for idempotent upserts). Auto-generated if omitted.",
            ),
            ParameterSchema::optional(
                "metadata",
                "object",
                "Arbitrary metadata to attach: {source, url, step, type, ...}.",
            ),
        ]
    }

    fn output_schema(&self) -> Option<serde_json::Value> {
        Some(serde_json::json!({
            "type": "object",
            "required": ["stored", "doc_id", "model", "dimensions", "chars"],
            "properties": {
                "stored": schema_boolean(),
                "doc_id": schema_string(),
                "model": schema_string(),
                "dimensions": schema_integer(),
                "chars": schema_integer(),
            },
            "additionalProperties": true,
        }))
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        let content = match args["content"].as_str() {
            Some(c) => c,
            None => return Ok(ToolResult::err("'content' required")),
        };
        let agent_id = match args["agent_id"].as_str() {
            Some(a) => a,
            None => return Ok(ToolResult::err("'agent_id' required")),
        };
        let tenant_id = match args["tenant_id"].as_str() {
            Some(t) => t,
            None => return Ok(ToolResult::err("'tenant_id' required")),
        };
        let metadata = args["metadata"].clone();

        // Embed the content
        let embedding = match self.embedder.embed(content).await {
            Ok(e) => e,
            Err(e) => return Ok(ToolResult::err(format!("embedding failed: {}", e))),
        };

        let mut doc = VectorDocument::new(tenant_id.to_string(), agent_id.to_string(), content.to_string(), embedding);

        // Allow caller to specify doc_id for idempotent upserts
        if let Some(id) = args["doc_id"].as_str() {
            doc.id = id.to_string();
        }
        if !metadata.is_null() {
            doc.metadata = metadata;
        }

        let doc_id = doc.id.clone();

        match self.store.upsert(doc).await {
            Ok(()) => Ok(ToolResult::ok(serde_json::json!({
                "stored":     true,
                "doc_id":     doc_id,
                "model":      self.embedder.model_name(),
                "dimensions": self.embedder.dimension(),
                "chars":      content.len(),
            }))),
            Err(e) => Ok(ToolResult::err(format!("store failed: {}", e))),
        }
    }
}

}
pub mod vector_search {
//! vector_search — Semantic search over agent memory using pgvector.
//!
//! Embeds the query, then returns the most semantically similar stored documents.
//! Supports cross-agent search (search all docs for this tenant)
//! or scoped to a specific agent.

use std::sync::Arc;

use async_trait::async_trait;

use crate::{
    memory::{EmbeddingModel, PgVectorStore, VectorStore},
    tools::{ParameterSchema, Tool, ToolResult},
};

pub struct VectorSearchTool {
    pub store: Arc<PgVectorStore>,
    pub embedder: Arc<dyn EmbeddingModel>,
}

#[async_trait]
impl Tool for VectorSearchTool {
    fn name(&self) -> &str {
        "vector_search"
    }
    fn description(&self) -> &str {
        "Search the agent's semantic memory using a natural language query. \
         Returns the most relevant stored documents ranked by cosine similarity. \
         Use after vector_store to retrieve previously stored knowledge."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::required("query", "string", "Natural language search query."),
            ParameterSchema::required("tenant_id", "string", "Tenant ID — injected automatically."),
            ParameterSchema::optional(
                "agent_id",
                "string",
                "Scope search to this agent only. Omit to search across all agents.",
            ),
            ParameterSchema::optional("top_k", "integer", "Max results to return (default: 5, max: 20)."),
            ParameterSchema::optional(
                "min_score",
                "number",
                "Minimum similarity score 0.0–1.0 (default: 0.3). Higher = stricter.",
            ),
        ]
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        let query = match args["query"].as_str() {
            Some(q) => q,
            None => return Ok(ToolResult::err("'query' required")),
        };
        let tenant_id = match args["tenant_id"].as_str() {
            Some(t) => t,
            None => return Ok(ToolResult::err("'tenant_id' required")),
        };
        let agent_id = args["agent_id"].as_str();
        let top_k = args["top_k"].as_u64().unwrap_or(5).min(20) as usize;
        let min_score = args["min_score"].as_f64().unwrap_or(0.3) as f32;

        // Embed the query
        let query_embedding = match self.embedder.embed(query).await {
            Ok(e) => e,
            Err(e) => return Ok(ToolResult::err(format!("embedding failed: {}", e))),
        };

        match self.store.search(tenant_id, agent_id, query_embedding, top_k, min_score).await {
            Ok(results) => {
                let docs: Vec<serde_json::Value> = results
                    .iter()
                    .map(|r| {
                        serde_json::json!({
                            "doc_id":   r.document.id,
                            "agent_id": r.document.agent_id,
                            "score":    (r.score * 1000.0).round() / 1000.0,
                            "content":  crate::util::truncate(&r.document.content, 2000),
                            "metadata": r.document.metadata,
                            "stored_at": r.document.created_at,
                        })
                    })
                    .collect();

                Ok(ToolResult::ok(serde_json::json!({
                    "query":      query,
                    "count":      docs.len(),
                    "results":    docs,
                    "model":      self.embedder.model_name(),
                    "scope":      agent_id.unwrap_or("all agents"),
                })))
            }
            Err(e) => Ok(ToolResult::err(format!("search failed: {}", e))),
        }
    }
}

}
pub mod vector_delete {
//! vector_delete — Remove documents from semantic memory.

use std::sync::Arc;

use async_trait::async_trait;

use crate::{
    memory::{PgVectorStore, VectorStore},
    tools::{ParameterSchema, Tool, ToolResult},
};

pub struct VectorDeleteTool {
    pub store: Arc<PgVectorStore>,
}

#[async_trait]
impl Tool for VectorDeleteTool {
    fn name(&self) -> &str {
        "vector_delete"
    }
    fn description(&self) -> &str {
        "Delete documents from semantic memory. Either delete a specific document by ID, \
         or clear all memory for an agent."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::required("tenant_id", "string", "Tenant ID — injected automatically."),
            ParameterSchema::optional("doc_id", "string", "Specific document ID to delete."),
            ParameterSchema::optional("agent_id", "string", "Delete ALL documents for this agent. Use with caution."),
        ]
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        let tenant_id = match args["tenant_id"].as_str() {
            Some(t) => t,
            None => return Ok(ToolResult::err("'tenant_id' required")),
        };

        if let Some(doc_id) = args["doc_id"].as_str() {
            match self.store.delete(tenant_id, doc_id).await {
                Ok(()) => Ok(ToolResult::ok(serde_json::json!({"deleted": true, "doc_id": doc_id}))),
                Err(e) => Ok(ToolResult::err(format!("delete failed: {}", e))),
            }
        } else if let Some(agent_id) = args["agent_id"].as_str() {
            match self.store.delete_by_agent(tenant_id, agent_id).await {
                Ok(n) => Ok(ToolResult::ok(serde_json::json!({"deleted": n, "agent_id": agent_id}))),
                Err(e) => Ok(ToolResult::err(format!("delete_by_agent failed: {}", e))),
            }
        } else {
            Ok(ToolResult::err("'doc_id' or 'agent_id' is required"))
        }
    }
}

}

// Re-exports
pub use vector_store::VectorStoreTool;
pub use vector_search::VectorSearchTool;
pub use vector_delete::VectorDeleteTool;
