//! Combined module Auto-generated by Narayan Refactor

pub mod wasm_compile {
//! wasm_compile — Compile WAT (WebAssembly Text format) to binary .wasm.
//!
//! Agents can write human-readable WAT then compile it to binary for wasm_exec.
//! Also validates existing .wasm files and reports module exports/imports.

use async_trait::async_trait;

use crate::tools::{ParameterSchema, Tool, ToolResult, schema_string, schema_boolean, schema_integer, schema_array};

pub struct WasmCompileTool;

#[async_trait]
impl Tool for WasmCompileTool {
    fn name(&self) -> &str {
        "wasm_compile"
    }
    fn description(&self) -> &str {
        "Compile WAT (WebAssembly Text Format) source to a .wasm binary, \
         or validate and inspect an existing .wasm file. \
         Returns the base64-encoded binary and module metadata (exports, imports, size). \
         Use wasm_exec to run the result."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::optional("wat", "string", "WAT source text to compile to WASM."),
            ParameterSchema::optional("wat_path", "string", "Path to a .wat source file to compile."),
            ParameterSchema::optional("wasm_path", "string", "Path to an existing .wasm to validate and inspect."),
            ParameterSchema::optional("output", "string", "Output path for the compiled .wasm (optional)."),
        ]
    }

    fn output_schema(&self) -> Option<serde_json::Value> {
        Some(serde_json::json!({
            "type": "object",
            "required": ["valid", "size_bytes", "exports", "imports", "bytes_b64", "tip"],
            "properties": {
                "valid": schema_boolean(),
                "size_bytes": schema_integer(),
                "exports": schema_array(serde_json::json!({
                    "type": "object",
                    "required": ["name", "type"],
                    "properties": {
                        "name": schema_string(),
                        "type": schema_string(),
                    },
                    "additionalProperties": true,
                })),
                "imports": schema_array(serde_json::json!({
                    "type": "object",
                    "required": ["module", "name", "type"],
                    "properties": {
                        "module": schema_string(),
                        "name": schema_string(),
                        "type": schema_string(),
                    },
                    "additionalProperties": true,
                })),
                "bytes_b64": schema_string(),
                "tip": schema_string(),
            },
            "additionalProperties": true,
        }))
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        use base64::Engine;
        use wasmtime::Engine as WasmEngine;

        // ── Load WAT or WASM ──────────────────────────────────────────────
        let wasm_bytes: Vec<u8> = if let Some(wat_src) = args["wat"].as_str() {
            match wat::parse_str(wat_src) {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("WAT parse error: {}", e))),
            }
        } else if let Some(wat_path) = args["wat_path"].as_str() {
            let src = match tokio::fs::read_to_string(wat_path).await {
                Ok(s) => s,
                Err(e) => return Ok(ToolResult::err(format!("read '{}': {}", wat_path, e))),
            };
            match wat::parse_str(&src) {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("WAT parse error: {}", e))),
            }
        } else if let Some(wasm_path) = args["wasm_path"].as_str() {
            match tokio::fs::read(wasm_path).await {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("read '{}': {}", wasm_path, e))),
            }
        } else {
            return Ok(ToolResult::err("one of 'wat', 'wat_path', or 'wasm_path' is required"));
        };

        if wasm_bytes.len() < 4 || &wasm_bytes[..4] != b"\0asm" {
            return Ok(ToolResult::err("resulting binary is not valid WASM"));
        }

        // ── Validate via wasmtime ─────────────────────────────────────────
        let engine = WasmEngine::default();
        let module = match wasmtime::Module::from_binary(&engine, &wasm_bytes) {
            Ok(m) => m,
            Err(e) => return Ok(ToolResult::err(format!("WASM validation failed: {}", e))),
        };

        // ── Collect module info ────────────────────────────────────────────
        let exports: Vec<serde_json::Value> = module
            .exports()
            .map(|e| serde_json::json!({ "name": e.name(), "type": format!("{:?}", e.ty()) }))
            .collect();
        let imports: Vec<serde_json::Value> = module
            .imports()
            .map(|i| serde_json::json!({ "module": i.module(), "name": i.name(), "type": format!("{:?}", i.ty()) }))
            .collect();

        // ── Optionally save to disk ────────────────────────────────────────
        if let Some(out_path) = args["output"].as_str() {
            if let Some(parent) = std::path::Path::new(out_path).parent() {
                tokio::fs::create_dir_all(parent).await.ok();
            }
            tokio::fs::write(out_path, &wasm_bytes)
                .await
                .map_err(|e| anyhow::anyhow!("write '{}': {}", out_path, e))?;
        }

        let b64 = base64::engine::general_purpose::STANDARD.encode(&wasm_bytes);

        Ok(ToolResult::ok(serde_json::json!({
            "valid":       true,
            "size_bytes":  wasm_bytes.len(),
            "exports":     exports,
            "imports":     imports,
            "bytes_b64":   b64,
            "tip":         "Pass bytes_b64 directly to wasm_exec to run this module.",
        })))
    }
}

#[cfg(test)]
mod tests {
    use base64::Engine;
    use tempfile::tempdir;

    use super::*;
    use crate::tools::Tool;

    fn sample_wat() -> &'static str {
        r#"(module
            (func (export "add") (param i32 i32) (result i32)
                local.get 0
                local.get 1
                i32.add)
        )"#
    }

    #[tokio::test]
    async fn test_execute_compiles_wat_and_reports_exports() {
        let tool = WasmCompileTool;

        let result = tool.execute(serde_json::json!({ "wat": sample_wat() })).await.expect("tool should execute");

        assert!(result.success);
        assert_eq!(result.output["valid"], serde_json::json!(true));
        assert!(result.output["size_bytes"].as_u64().unwrap_or_default() > 8);
        assert!(result.output["bytes_b64"].as_str().unwrap_or_default().len() > 10);
        assert!(result.output["exports"]
            .as_array()
            .map(|exports| exports.iter().any(|export| export["name"] == serde_json::json!("add")))
            .unwrap_or(false));
    }

    #[tokio::test]
    async fn test_execute_writes_output_file_and_can_reinspect_saved_wasm() {
        let tool = WasmCompileTool;
        let dir = tempdir().expect("tempdir should exist");
        let output = dir.path().join("nested").join("module.wasm");

        let compiled = tool
            .execute(serde_json::json!({
                "wat": sample_wat(),
                "output": output.to_string_lossy().to_string(),
            }))
            .await
            .expect("compile should succeed");

        assert!(compiled.success);
        assert!(output.exists());

        let saved_bytes = tokio::fs::read(&output).await.expect("saved wasm should be readable");
        let encoded = compiled.output["bytes_b64"].as_str().expect("encoded bytes should exist");
        let decoded = base64::engine::general_purpose::STANDARD.decode(encoded).expect("base64 should decode");
        assert_eq!(decoded, saved_bytes);

        let reinspected = tool
            .execute(serde_json::json!({ "wasm_path": output.to_string_lossy().to_string() }))
            .await
            .expect("wasm validation should succeed");
        assert!(reinspected.success);
        assert_eq!(reinspected.output["valid"], serde_json::json!(true));
    }

    #[tokio::test]
    async fn test_execute_rejects_invalid_wat_and_missing_input() {
        let tool = WasmCompileTool;

        let missing = tool.execute(serde_json::json!({})).await.expect("tool should execute");
        assert!(!missing.success);
        assert!(missing.error.unwrap_or_default().contains("one of 'wat', 'wat_path', or 'wasm_path'"));

        let invalid = tool.execute(serde_json::json!({ "wat": "(module (func" })).await.expect("tool should execute");
        assert!(!invalid.success);
        assert!(invalid.error.unwrap_or_default().contains("WAT parse error"));
    }
}

}
pub mod wasm_exec {
//! wasm_exec — Execute a WebAssembly module with WASI 0.2 (stable, 2026).
//!
//! Runs .wasm binaries in a fully isolated sandbox:
//!   - stdin/stdout/stderr captured in memory
//!   - Filesystem scoped to workspace dir only  
//!   - Allowlisted env vars only
//!   - Strict fuel + timeout + memory limits

use async_trait::async_trait;

use crate::tools::{ParameterSchema, Tool, ToolResult, schema_string, schema_boolean, schema_integer, schema_array};

pub struct WasmExecTool;

const DEFAULT_TIMEOUT_SECS: u64 = 3;
const MAX_TIMEOUT_SECS: u64 = 15;
const DEFAULT_FUEL: u64 = 5_000_000;
const MAX_FUEL: u64 = 20_000_000;
const DEFAULT_MEMORY_LIMIT_BYTES: u64 = 16 * 1024 * 1024;
const MAX_MEMORY_LIMIT_BYTES: u64 = 64 * 1024 * 1024;

#[async_trait]
impl Tool for WasmExecTool {
    fn name(&self) -> &str {
        "wasm_exec"
    }
    fn description(&self) -> &str {
        "Execute a WebAssembly module with full WASI 0.2 sandboxing. \
         Accepts a .wasm file path or base64-encoded bytes. \
         Stdin, args, and env vars are configurable. Stdout/stderr are captured. \
         Filesystem is scoped to workspace only. CPU bounded by fuel."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::optional("path", "string", "Path to a .wasm file to execute."),
            ParameterSchema::optional("bytes_b64", "string", "Base64-encoded .wasm bytes (alternative to path)."),
            ParameterSchema::optional("stdin", "string", "Text to pass to the module on stdin."),
            ParameterSchema::optional("args", "array", "Command-line arguments passed to the module."),
            ParameterSchema::optional("env", "object", "Environment variables: {KEY: value}."),
            ParameterSchema::optional("workspace", "string", "Directory mounted as /workspace (read-write)."),
            ParameterSchema::optional("timeout_secs", "integer", "Hard timeout in seconds (default: 3, max: 15)."),
            ParameterSchema::optional("fuel", "integer", "Max WASM fuel (default: 5,000,000; max: 20,000,000)."),
            ParameterSchema::optional(
                "memory_limit_bytes",
                "integer",
                "Linear memory limit in bytes (default: 16MB, max: 64MB).",
            ),
        ]
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        use base64::Engine;

        let wasm_bytes: Vec<u8> = if let Some(p) = args["path"].as_str() {
            match tokio::fs::read(p).await {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("read '{}': {}", p, e))),
            }
        } else if let Some(b64) = args["bytes_b64"].as_str() {
            match base64::engine::general_purpose::STANDARD.decode(b64) {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("base64 decode: {}", e))),
            }
        } else {
            return Ok(ToolResult::err("'path' or 'bytes_b64' is required"));
        };

        if wasm_bytes.len() < 4 || &wasm_bytes[..4] != b"\0asm" {
            return Ok(ToolResult::err("invalid WebAssembly binary — missing \\0asm magic"));
        }

        let stdin_data = args["stdin"].as_str().unwrap_or("").to_string();
        let timeout_secs = args["timeout_secs"].as_u64().unwrap_or(DEFAULT_TIMEOUT_SECS).clamp(1, MAX_TIMEOUT_SECS);
        let fuel_limit = args["fuel"].as_u64().unwrap_or(DEFAULT_FUEL).clamp(100_000, MAX_FUEL);
        let memory_limit_bytes = args["memory_limit_bytes"]
            .as_u64()
            .unwrap_or(DEFAULT_MEMORY_LIMIT_BYTES)
            .clamp(1 * 1024 * 1024, MAX_MEMORY_LIMIT_BYTES);
        let workspace = args["workspace"].as_str().unwrap_or(".").to_string();
        let wasm_size = wasm_bytes.len();

        let cli_args: Vec<String> =
            args["args"].as_array().unwrap_or(&vec![]).iter().filter_map(|v| v.as_str().map(String::from)).collect();

        let env_vars: Vec<(String, String)> = args["env"]
            .as_object()
            .map(|o| o.iter().filter_map(|(k, v)| v.as_str().map(|s| (k.clone(), s.to_string()))).collect())
            .unwrap_or_default();

        let join = tokio::task::spawn_blocking(move || {
            run_wasm(wasm_bytes, stdin_data, cli_args, env_vars, workspace, fuel_limit, memory_limit_bytes)
        });

        match tokio::time::timeout(std::time::Duration::from_secs(timeout_secs), join).await {
            Ok(Ok(Ok(mut v))) => {
                v["wasm_size_bytes"] = serde_json::json!(wasm_size);
                v["memory_limit_bytes"] = serde_json::json!(memory_limit_bytes);
                v["fuel_limit"] = serde_json::json!(fuel_limit);
                Ok(ToolResult::ok(v))
            }
            Ok(Ok(Err(e))) => Ok(ToolResult::err(format!("WASM error: {}", e))),
            Ok(Err(e)) => Ok(ToolResult::err(format!("thread panic: {}", e))),
            Err(_) => Ok(ToolResult::err(format!("timed out after {}s", timeout_secs))),
        }
    }
}

fn run_wasm(
    bytes: Vec<u8>,
    stdin_data: String,
    args: Vec<String>,
    env_vars: Vec<(String, String)>,
    workspace: String,
    fuel: u64,
    memory_limit_bytes: u64,
) -> anyhow::Result<serde_json::Value> {
    use std::time::Instant;

    use wasmtime::*;
    use wasmtime_wasi::{
        pipe::{MemoryInputPipe, MemoryOutputPipe},
        preview1::{self, WasiP1Ctx},
        WasiCtxBuilder,
    };

    let t0 = Instant::now();
    let mut cfg = Config::new();
    cfg.async_support(false);
    cfg.consume_fuel(true);
    let engine = Engine::new(&cfg)?;

    let stdout_pipe = MemoryOutputPipe::new(512 * 1024);
    let stderr_pipe = MemoryOutputPipe::new(256 * 1024);
    let stdout_read = stdout_pipe.clone();
    let stderr_read = stderr_pipe.clone();

    let mut wb = WasiCtxBuilder::new();
    if !stdin_data.is_empty() {
        wb.stdin(MemoryInputPipe::new(stdin_data.into_bytes()));
    }
    wb.stdout(stdout_pipe).stderr(stderr_pipe);
    wb.args(&args);
    for (k, v) in &env_vars {
        wb.env(k, v);
    }

    let ws = std::path::Path::new(&workspace);
    if ws.exists() {
        wb.preopened_dir(ws, "/workspace", wasmtime_wasi::DirPerms::all(), wasmtime_wasi::FilePerms::all())?;
    }
    let wasi = wb.build_p1();
    let limits = StoreLimitsBuilder::new()
        .memory_size((memory_limit_bytes.min(usize::MAX as u64)) as usize)
        .instances(1)
        .tables(2)
        .memories(1)
        .build();
    let mut store = Store::new(&engine, (wasi, limits));
    store.limiter(|state| &mut state.1);
    store.set_fuel(fuel)?;

    let mut linker: Linker<(WasiP1Ctx, wasmtime::StoreLimits)> = Linker::new(&engine);
    preview1::add_to_linker_sync(&mut linker, |state| &mut state.0)?;

    let module = Module::from_binary(&engine, &bytes)?;
    let instance = linker.instantiate(&mut store, &module)?;

    let exit_code: i32 = match instance.get_typed_func::<(), ()>(&mut store, "_start") {
        Ok(f) => match f.call(&mut store, ()) {
            Ok(()) => 0,
            Err(e) => e.downcast_ref::<wasmtime_wasi::I32Exit>().map(|x| x.0).unwrap_or(1),
        },
        Err(_) => {
            if let Ok(f) = instance.get_typed_func::<(), ()>(&mut store, "_initialize") {
                f.call(&mut store, ())?;
            }
            0
        }
    };

    let fuel_used = store.get_fuel().ok().map(|remaining| fuel.saturating_sub(remaining));
    let stdout = String::from_utf8_lossy(&stdout_read.try_into_inner().unwrap_or_default()).into_owned();
    let stderr = String::from_utf8_lossy(&stderr_read.try_into_inner().unwrap_or_default()).into_owned();
    let elapsed_ms = t0.elapsed().as_millis() as u64;

    tracing::info!(exit_code, elapsed_ms, fuel_used = ?fuel_used, "WASM executed");

    Ok(serde_json::json!({
        "exit_code":  exit_code,
        "success":    exit_code == 0,
        "stdout":     crate::util::truncate(&stdout, 50_000),
        "stderr":     crate::util::truncate(&stderr, 10_000),
        "elapsed_ms": elapsed_ms,
        "fuel_used":  fuel_used,
    }))
}

#[cfg(test)]
mod tests {
    use base64::Engine;
    use tempfile::tempdir;

    use super::*;
    use crate::tools::Tool;

    fn encode_wat(wat: &str) -> String {
        let bytes = wat::parse_str(wat).expect("wat should compile");
        base64::engine::general_purpose::STANDARD.encode(bytes)
    }

    #[tokio::test]
    async fn test_execute_runs_wasi_command_module_through_start() {
        let tool = WasmExecTool;
        let dir = tempdir().expect("tempdir should exist");
        let module = encode_wat(r#"(module (func (export "_start")))"#);

        let result = tool
            .execute(serde_json::json!({
                "bytes_b64": module,
                "workspace": dir.path().to_string_lossy().to_string(),
                "timeout_secs": 5,
            }))
            .await
            .expect("tool should execute");

        assert!(result.success);
        assert_eq!(result.output["exit_code"], serde_json::json!(0));
        assert_eq!(result.output["success"], serde_json::json!(true));
        assert_eq!(result.output["stdout"], serde_json::json!(""));
        assert_eq!(result.output["stderr"], serde_json::json!(""));
        assert!(result.output["wasm_size_bytes"].as_u64().unwrap_or_default() > 8);
    }

    #[tokio::test]
    async fn test_execute_runs_reactor_initialize_when_start_is_missing() {
        let tool = WasmExecTool;
        let dir = tempdir().expect("tempdir should exist");
        let module = encode_wat(r#"(module (func (export "_initialize")))"#);

        let result = tool
            .execute(serde_json::json!({
                "bytes_b64": module,
                "workspace": dir.path().to_string_lossy().to_string(),
            }))
            .await
            .expect("tool should execute");

        assert!(result.success);
        assert_eq!(result.output["exit_code"], serde_json::json!(0));
        assert_eq!(result.output["success"], serde_json::json!(true));
    }

    #[tokio::test]
    async fn test_execute_rejects_invalid_binary_before_runtime() {
        let tool = WasmExecTool;

        let result = tool
            .execute(serde_json::json!({
                "bytes_b64": base64::engine::general_purpose::STANDARD.encode("not-wasm"),
            }))
            .await
            .expect("tool should execute");

        assert!(!result.success);
        assert!(result.error.unwrap_or_default().contains("invalid WebAssembly binary"));
    }
}

}
pub mod wasm_call {
//! wasm_call — Call a specific exported function in a WASM module directly.
//!
//! Unlike wasm_exec (which runs _start / the full WASI command), wasm_call
//! targets a named export. Useful for:
//!   - Reactor modules (library-style WASM without _start)
//!   - Calling specific functions for computation
//!   - Running pure functions with typed i32/i64/f32/f64 arguments

use async_trait::async_trait;

use crate::tools::{ParameterSchema, Tool, ToolResult, schema_string, schema_boolean, schema_integer, schema_array};

pub struct WasmCallTool;

const DEFAULT_TIMEOUT_SECS: u64 = 3;
const MAX_TIMEOUT_SECS: u64 = 15;
const DEFAULT_FUEL: u64 = 3_000_000;
const MAX_FUEL: u64 = 20_000_000;
const DEFAULT_MEMORY_LIMIT_BYTES: u64 = 16 * 1024 * 1024;
const MAX_MEMORY_LIMIT_BYTES: u64 = 64 * 1024 * 1024;

#[async_trait]
impl Tool for WasmCallTool {
    fn name(&self) -> &str {
        "wasm_call"
    }
    fn description(&self) -> &str {
        "Call a specific exported function in a WebAssembly module by name. \
         Supports i32, i64, f32, f64 arguments and return values. \
         For WASI command modules with _start, use wasm_exec instead."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::optional("path", "string", "Path to .wasm file."),
            ParameterSchema::optional("bytes_b64", "string", "Base64-encoded .wasm bytes."),
            ParameterSchema::required("function", "string", "Name of the exported function to call."),
            ParameterSchema::optional("args", "array", "Function arguments as numbers or strings ('1', '3.14')."),
            ParameterSchema::optional("fuel", "integer", "Max fuel (default: 3,000,000; max: 20,000,000)."),
            ParameterSchema::optional("timeout_secs", "integer", "Hard timeout in seconds (default: 3, max: 15)."),
            ParameterSchema::optional(
                "memory_limit_bytes",
                "integer",
                "Linear memory limit in bytes (default: 16MB, max: 64MB).",
            ),
        ]
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        use base64::Engine;

        let bytes: Vec<u8> = if let Some(p) = args["path"].as_str() {
            match tokio::fs::read(p).await {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("read '{}': {}", p, e))),
            }
        } else if let Some(b64) = args["bytes_b64"].as_str() {
            match base64::engine::general_purpose::STANDARD.decode(b64) {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("base64: {}", e))),
            }
        } else {
            return Ok(ToolResult::err("'path' or 'bytes_b64' required"));
        };

        let func_name = match args["function"].as_str() {
            Some(f) => f.to_string(),
            None => return Ok(ToolResult::err("'function' is required")),
        };

        let fuel = args["fuel"].as_u64().unwrap_or(DEFAULT_FUEL).clamp(100_000, MAX_FUEL);
        let timeout_secs = args["timeout_secs"].as_u64().unwrap_or(DEFAULT_TIMEOUT_SECS).clamp(1, MAX_TIMEOUT_SECS);
        let memory_limit_bytes = args["memory_limit_bytes"]
            .as_u64()
            .unwrap_or(DEFAULT_MEMORY_LIMIT_BYTES)
            .clamp(1 * 1024 * 1024, MAX_MEMORY_LIMIT_BYTES);
        let raw_args: Vec<serde_json::Value> = args["args"].as_array().cloned().unwrap_or_default();

        let join =
            tokio::task::spawn_blocking(move || call_wasm_func(bytes, func_name, raw_args, fuel, memory_limit_bytes));

        match tokio::time::timeout(std::time::Duration::from_secs(timeout_secs), join).await {
            Err(_) => Ok(ToolResult::err(format!("timed out after {}s", timeout_secs))),
            Ok(Ok(Ok(v))) => Ok(ToolResult::ok(v)),
            Ok(Ok(Err(e))) => Ok(ToolResult::err(format!("wasm_call error: {}", e))),
            Ok(Err(e)) => Ok(ToolResult::err(format!("thread panic: {}", e))),
        }
    }
}

fn call_wasm_func(
    bytes: Vec<u8>,
    func_name: String,
    raw_args: Vec<serde_json::Value>,
    fuel: u64,
    memory_limit_bytes: u64,
) -> anyhow::Result<serde_json::Value> {
    use std::time::Instant;

    use wasmtime::*;

    let t0 = Instant::now();
    let mut cfg = Config::new();
    cfg.async_support(false);
    cfg.consume_fuel(true);
    let engine = Engine::new(&cfg)?;

    let module = Module::from_binary(&engine, &bytes)?;
    let limits = StoreLimitsBuilder::new()
        .memory_size((memory_limit_bytes.min(usize::MAX as u64)) as usize)
        .instances(1)
        .tables(2)
        .memories(1)
        .build();
    let mut store: Store<wasmtime::StoreLimits> = Store::new(&engine, limits);
    store.limiter(|limits| limits);
    store.set_fuel(fuel)?;
    let linker: Linker<wasmtime::StoreLimits> = Linker::new(&engine);
    let instance = linker.instantiate(&mut store, &module)?;

    let func = instance
        .get_func(&mut store, &func_name)
        .ok_or_else(|| anyhow::anyhow!("function '{}' not found — use wasm_inspect to list exports", func_name))?;

    let func_ty = func.ty(&store);

    // Convert JSON args to wasmtime Val based on function type signature
    let wasm_args: Vec<Val> = func_ty
        .params()
        .zip(raw_args.iter().chain(std::iter::repeat(&serde_json::Value::Null)))
        .map(|(ty, v)| json_to_val(v, ty))
        .collect::<Result<Vec<_>, _>>()?;

    let mut results = vec![Val::I32(0); func_ty.results().len()];
    func.call(&mut store, &wasm_args, &mut results)?;

    let fuel_used = store.get_fuel().ok().map(|remaining| fuel.saturating_sub(remaining));
    let elapsed_ms = t0.elapsed().as_millis() as u64;

    let result_vals: Vec<serde_json::Value> = results.iter().map(val_to_json).collect();
    let result = if result_vals.len() == 1 { result_vals[0].clone() } else { serde_json::json!(result_vals) };

    Ok(serde_json::json!({
        "function":   func_name,
        "result":     result,
        "elapsed_ms": elapsed_ms,
        "fuel_used":  fuel_used,
        "fuel_limit": fuel,
        "memory_limit_bytes": memory_limit_bytes,
        "success":    true,
    }))
}

fn json_to_val(v: &serde_json::Value, ty: wasmtime::ValType) -> anyhow::Result<wasmtime::Val> {
    use wasmtime::ValType;
    match ty {
        ValType::I32 => Ok(wasmtime::Val::I32(
            v.as_i64().unwrap_or_else(|| v.as_str().and_then(|s| s.parse().ok()).unwrap_or(0)) as i32,
        )),
        ValType::I64 => {
            Ok(wasmtime::Val::I64(v.as_i64().unwrap_or_else(|| v.as_str().and_then(|s| s.parse().ok()).unwrap_or(0))))
        }
        ValType::F32 => Ok(wasmtime::Val::F32(
            (v.as_f64().unwrap_or_else(|| v.as_str().and_then(|s| s.parse().ok()).unwrap_or(0.0)) as f32).to_bits(),
        )),
        ValType::F64 => Ok(wasmtime::Val::F64(
            v.as_f64().unwrap_or_else(|| v.as_str().and_then(|s| s.parse().ok()).unwrap_or(0.0)).to_bits(),
        )),
        other => anyhow::bail!("unsupported WASM type {:?} — only i32/i64/f32/f64 supported", other),
    }
}

fn val_to_json(v: &wasmtime::Val) -> serde_json::Value {
    match v {
        wasmtime::Val::I32(n) => serde_json::json!(n),
        wasmtime::Val::I64(n) => serde_json::json!(n),
        wasmtime::Val::F32(b) => serde_json::json!(f32::from_bits(*b)),
        wasmtime::Val::F64(b) => serde_json::json!(f64::from_bits(*b)),
        other => serde_json::json!(format!("{:?}", other)),
    }
}

#[cfg(test)]
mod tests {
    use base64::Engine;

    use super::*;
    use crate::tools::Tool;

    fn add_module_b64() -> String {
        let bytes = wat::parse_str(
            r#"(module
                (func (export "add") (param i32 i32) (result i32)
                    local.get 0
                    local.get 1
                    i32.add)
            )"#,
        )
        .expect("wat should compile");
        base64::engine::general_purpose::STANDARD.encode(bytes)
    }

    #[tokio::test]
    async fn test_execute_calls_exported_function_and_coerces_args() {
        let tool = WasmCallTool;

        let result = tool
            .execute(serde_json::json!({
                "bytes_b64": add_module_b64(),
                "function": "add",
                "args": ["2", 3],
                "fuel": 10_000,
            }))
            .await
            .expect("tool should execute");

        assert!(result.success);
        assert_eq!(result.output["function"], serde_json::json!("add"));
        assert_eq!(result.output["result"], serde_json::json!(5));
        assert_eq!(result.output["success"], serde_json::json!(true));
    }

    #[tokio::test]
    async fn test_execute_reports_missing_function_cleanly() {
        let tool = WasmCallTool;

        let result = tool
            .execute(serde_json::json!({
                "bytes_b64": add_module_b64(),
                "function": "missing_export",
            }))
            .await
            .expect("tool should execute");

        assert!(!result.success);
        assert!(result.error.unwrap_or_default().contains("function 'missing_export' not found"));
    }

    #[tokio::test]
    async fn test_execute_requires_source_and_function() {
        let tool = WasmCallTool;

        let no_source = tool.execute(serde_json::json!({ "function": "add" })).await.expect("tool should execute");
        assert!(!no_source.success);
        assert!(no_source.error.unwrap_or_default().contains("'path' or 'bytes_b64' required"));

        let no_function =
            tool.execute(serde_json::json!({ "bytes_b64": add_module_b64() })).await.expect("tool should execute");
        assert!(!no_function.success);
        assert!(no_function.error.unwrap_or_default().contains("'function' is required"));
    }
}

}
pub mod wasm_inspect {
//! wasm_inspect — Deep static analysis of a WebAssembly module.
//!
//! Without executing anything, extracts:
//!   - All exports and their types (functions, globals, tables, memories)
//!   - All imports and their types
//!   - Custom sections (name section, WASI version hints, build metadata)
//!   - Memory/table/global counts and limits
//!   - Function count and estimated code size
//!   - Whether the module targets WASI command or reactor interface

use async_trait::async_trait;

use crate::tools::{ParameterSchema, Tool, ToolResult, schema_string, schema_boolean, schema_integer, schema_array};

pub struct WasmInspectTool;

#[async_trait]
impl Tool for WasmInspectTool {
    fn name(&self) -> &str {
        "wasm_inspect"
    }
    fn description(&self) -> &str {
        "Statically inspect a WebAssembly module without executing it. \
         Returns exports, imports, memory layout, section info, and whether \
         the module is a WASI command, reactor, or bare module."
    }
    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::optional("path", "string", "Path to .wasm file."),
            ParameterSchema::optional("bytes_b64", "string", "Base64-encoded .wasm bytes."),
        ]
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        use base64::Engine;

        let bytes: Vec<u8> = if let Some(p) = args["path"].as_str() {
            match tokio::fs::read(p).await {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("read '{}': {}", p, e))),
            }
        } else if let Some(b64) = args["bytes_b64"].as_str() {
            match base64::engine::general_purpose::STANDARD.decode(b64) {
                Ok(b) => b,
                Err(e) => return Ok(ToolResult::err(format!("base64: {}", e))),
            }
        } else {
            return Ok(ToolResult::err("'path' or 'bytes_b64' required"));
        };

        if bytes.len() < 4 || &bytes[..4] != b"\0asm" {
            return Ok(ToolResult::err("not a valid WASM binary"));
        }

        let engine = wasmtime::Engine::default();
        let module = match wasmtime::Module::from_binary(&engine, &bytes) {
            Ok(m) => m,
            Err(e) => return Ok(ToolResult::err(format!("invalid WASM: {}", e))),
        };

        let exports: Vec<serde_json::Value> = module
            .exports()
            .map(|e| serde_json::json!({ "name": e.name(), "kind": classify_extern(&e.ty()) }))
            .collect();
        let imports: Vec<serde_json::Value> = module
            .imports()
            .map(|i| {
                serde_json::json!({
                    "module": i.module(),
                    "name":   i.name(),
                    "kind":   classify_extern(&i.ty()),
                })
            })
            .collect();

        let export_names: Vec<&str> = module.exports().map(|e| e.name()).collect();
        let import_modules: Vec<&str> = module.imports().map(|i| i.module()).collect();

        let interface = if export_names.contains(&"_start") {
            "wasi-command"
        } else if export_names.contains(&"_initialize") {
            "wasi-reactor"
        } else if import_modules.iter().any(|m| m.starts_with("wasi_")) {
            "wasi-unknown"
        } else {
            "bare-module"
        };

        let wasi_version = if import_modules.iter().any(|m| *m == "wasi_snapshot_preview1") {
            "WASI Preview 1"
        } else if import_modules.iter().any(|m| m.starts_with("wasi:")) {
            "WASI Preview 2 (component model)"
        } else {
            "none"
        };

        Ok(ToolResult::ok(serde_json::json!({
            "size_bytes":    bytes.len(),
            "interface":     interface,
            "wasi_version":  wasi_version,
            "exports":       exports,
            "export_count":  exports.len(),
            "imports":       imports,
            "import_count":  imports.len(),
            "has_start":     export_names.contains(&"_start"),
            "has_memory":    export_names.contains(&"memory"),
            "tip": match interface {
                "wasi-command"  => "Run with wasm_exec — it exports _start.",
                "wasi-reactor"  => "Reactor module — call exported functions directly via wasm_call.",
                "bare-module"   => "Bare module — use wasm_call to invoke specific exports.",
                _               => "Use wasm_exec or wasm_call depending on the interface.",
            },
        })))
    }
}

fn classify_extern(ty: &wasmtime::ExternType) -> &'static str {
    match ty {
        wasmtime::ExternType::Func(_) => "function",
        wasmtime::ExternType::Global(_) => "global",
        wasmtime::ExternType::Table(_) => "table",
        wasmtime::ExternType::Memory(_) => "memory",
        wasmtime::ExternType::Tag(_) => "tag",
    }
}

#[cfg(test)]
mod tests {
    use base64::Engine;

    use super::*;
    use crate::tools::Tool;

    fn encode_wat(wat: &str) -> String {
        let bytes = wat::parse_str(wat).expect("wat should compile");
        base64::engine::general_purpose::STANDARD.encode(bytes)
    }

    #[tokio::test]
    async fn test_execute_classifies_bare_module_exports_and_memory() {
        let tool = WasmInspectTool;
        let module = encode_wat(
            r#"(module
                (memory (export "memory") 1)
                (func (export "run"))
            )"#,
        );

        let result = tool.execute(serde_json::json!({ "bytes_b64": module })).await.expect("tool should execute");

        assert!(result.success);
        assert_eq!(result.output["interface"], serde_json::json!("bare-module"));
        assert_eq!(result.output["has_memory"], serde_json::json!(true));
        assert_eq!(result.output["export_count"], serde_json::json!(2));
        assert!(result.output["exports"]
            .as_array()
            .map(|exports| {
                exports.iter().any(|export| {
                    export["name"] == serde_json::json!("memory") && export["kind"] == serde_json::json!("memory")
                })
            })
            .unwrap_or(false));
        assert!(result.output["tip"].as_str().unwrap_or_default().contains("wasm_call"));
    }

    #[tokio::test]
    async fn test_execute_detects_command_interface_from_start_export() {
        let tool = WasmInspectTool;
        let module = encode_wat(r#"(module (func (export "_start")))"#);

        let result = tool.execute(serde_json::json!({ "bytes_b64": module })).await.expect("tool should execute");

        assert!(result.success);
        assert_eq!(result.output["interface"], serde_json::json!("wasi-command"));
        assert_eq!(result.output["has_start"], serde_json::json!(true));
        assert!(result.output["tip"].as_str().unwrap_or_default().contains("wasm_exec"));
    }

    #[tokio::test]
    async fn test_execute_rejects_invalid_binary() {
        let tool = WasmInspectTool;

        let result = tool
            .execute(serde_json::json!({
                "bytes_b64": base64::engine::general_purpose::STANDARD.encode("plain-text"),
            }))
            .await
            .expect("tool should execute");

        assert!(!result.success);
        assert!(result.error.unwrap_or_default().contains("not a valid WASM binary"));
    }
}

}
pub mod run_registered_wasm {
//! `run_registered_wasm` - execute tenant-registered WASM tools with strict limits.
//!
//! Unlike `wasm_exec` (raw module execution), this tool only runs modules that
//! were pre-registered by the tenant and stored in Postgres. Each registered tool
//! carries explicit permissions and hard resource limits (memory, fuel, timeout).

use std::{collections::HashSet, path::Path, sync::Arc, time::Instant};

use async_trait::async_trait;
use chrono::Utc;
use wasmtime::{Config, Engine, Linker, Module, Store, StoreLimitsBuilder};
use wasmtime_wasi::{
    pipe::{MemoryInputPipe, MemoryOutputPipe},
    preview1::{self, WasiP1Ctx},
    DirPerms, FilePerms, WasiCtxBuilder,
};

use crate::{
    agent::definition::{TenantWasmTool, WasmToolRunAudit},
    storage::PostgresStore,
    tools::{ParameterSchema, Tool, ToolResult},
};

const TOOL_NAME: &str = "run_registered_wasm";
const MAX_STDOUT_CAPTURE_BYTES: usize = 512 * 1024;
const MAX_STDERR_CAPTURE_BYTES: usize = 256 * 1024;

pub struct RunRegisteredWasmTool {
    store: Option<Arc<PostgresStore>>,
}

impl RunRegisteredWasmTool {
    pub fn new() -> Self {
        Self { store: None }
    }

    pub fn with_store(mut self, store: Arc<PostgresStore>) -> Self {
        self.store = Some(store);
        self
    }
}

#[async_trait]
impl Tool for RunRegisteredWasmTool {
    fn name(&self) -> &str {
        TOOL_NAME
    }

    fn description(&self) -> &str {
        "Run a tenant-registered WASM tool by name. \
         Enforces strict per-tool limits (memory, fuel, timeout) and sandbox permissions. \
         Use this for user-specific deterministic logic with low CPU/memory usage."
    }

    fn category(&self) -> &'static str {
        "other"
    }

    fn parameters_schema(&self) -> Vec<ParameterSchema> {
        vec![
            ParameterSchema::required("tool_name", "string", "Registered WASM tool name."),
            ParameterSchema::optional("input", "object", "JSON input payload. If provided, serialized to stdin."),
            ParameterSchema::optional("stdin", "string", "Raw stdin text. Overrides input serialization."),
            ParameterSchema::optional("args", "array", "CLI arguments passed to the module."),
            ParameterSchema::optional("env", "object", "Optional env vars. Keys outside allowlist are ignored."),
            ParameterSchema::optional("workspace", "string", "Workspace path (injected by executor)."),
            ParameterSchema::optional(
                "timeout_secs",
                "integer",
                "Requested timeout, capped by the registered tool timeout limit.",
            ),
            ParameterSchema::optional("fuel", "integer", "Requested fuel, capped by the registered tool fuel limit."),
            ParameterSchema::optional(
                "memory_limit_bytes",
                "integer",
                "Requested memory cap, capped by the registered tool memory limit.",
            ),
            ParameterSchema::optional("tenant_id", "string", "Injected by executor."),
            ParameterSchema::optional("agent_id", "string", "Injected by executor for audit."),
            ParameterSchema::optional("role_id", "string", "Injected by executor for audit."),
            ParameterSchema::optional("goal_instance_id", "string", "Injected by executor for audit."),
        ]
    }

    async fn execute(&self, args: serde_json::Value) -> anyhow::Result<ToolResult> {
        let Some(store) = self.store.as_ref() else {
            return Ok(ToolResult::err("store not configured for run_registered_wasm"));
        };

        let tenant_id = args["tenant_id"].as_str().unwrap_or("").trim();
        if tenant_id.is_empty() {
            return Ok(ToolResult::err("tenant_id is required (injected by executor)"));
        }

        let tool_name = args["tool_name"].as_str().unwrap_or("").trim().to_string();
        if tool_name.is_empty() {
            return Ok(ToolResult::err("'tool_name' is required"));
        }

        let Some((tool_meta, module_bytes)) = store.get_tenant_wasm_tool_with_module(tenant_id, &tool_name).await?
        else {
            return Ok(ToolResult::err(format!("registered WASM tool '{}' not found", tool_name)));
        };

        if !tool_meta.enabled {
            return Ok(ToolResult::err(format!("registered WASM tool '{}' is disabled", tool_name)));
        }
        if module_bytes.len() < 4 || &module_bytes[..4] != b"\0asm" {
            return Ok(ToolResult::err(format!("registered WASM tool '{}' has invalid module bytes", tool_name)));
        }

        let limits = tool_meta.limits.clamped();
        let effective_timeout =
            args["timeout_secs"].as_u64().unwrap_or(limits.timeout_secs).clamp(1, limits.timeout_secs);
        let effective_fuel = args["fuel"].as_u64().unwrap_or(limits.max_fuel).clamp(100_000, limits.max_fuel);
        let effective_memory = args["memory_limit_bytes"]
            .as_u64()
            .unwrap_or(limits.max_memory_bytes)
            .clamp(1 * 1024 * 1024, limits.max_memory_bytes);

        let stdin_data = build_stdin_payload(&args);
        let cli_args: Vec<String> = args["args"]
            .as_array()
            .unwrap_or(&vec![])
            .iter()
            .filter_map(|value| value.as_str().map(String::from))
            .collect();
        let env_vars = filter_allowed_env(&tool_meta, &args["env"]);

        let workspace = args["workspace"].as_str().map(str::trim).filter(|v| !v.is_empty()).map(String::from);

        let tool_version = tool_meta.version;
        let run_started = Instant::now();
        let join = tokio::task::spawn_blocking(move || {
            execute_registered_module(
                module_bytes,
                stdin_data,
                cli_args,
                env_vars,
                workspace,
                tool_meta,
                effective_memory,
                effective_fuel,
            )
        });

        let (success, output, error, elapsed_ms, fuel_used) =
            match tokio::time::timeout(std::time::Duration::from_secs(effective_timeout), join).await {
                Ok(Ok(Ok(run))) => (run.success, run.output, None, run.elapsed_ms, run.fuel_used),
                Ok(Ok(Err(err))) => (
                    false,
                    serde_json::Value::Null,
                    Some(format!("WASM execution error: {}", err)),
                    run_started.elapsed().as_millis() as u64,
                    None,
                ),
                Ok(Err(join_err)) => (
                    false,
                    serde_json::Value::Null,
                    Some(format!("WASM worker panic: {}", join_err)),
                    run_started.elapsed().as_millis() as u64,
                    None,
                ),
                Err(_) => (
                    false,
                    serde_json::Value::Null,
                    Some(format!("timed out after {}s", effective_timeout)),
                    run_started.elapsed().as_millis() as u64,
                    None,
                ),
            };

        let audit = WasmToolRunAudit {
            id: uuid::Uuid::new_v4().to_string(),
            tenant_id: tenant_id.to_string(),
            tool_name: tool_name.clone(),
            tool_version,
            agent_id: args["agent_id"].as_str().map(String::from),
            role_id: args["role_id"].as_str().map(String::from),
            goal_instance_id: args["goal_instance_id"].as_str().map(String::from),
            success,
            elapsed_ms,
            fuel_used,
            memory_limit_bytes: effective_memory,
            error: error.clone(),
            created_at: Utc::now(),
        };

        if let Err(e) = store.insert_wasm_tool_run_audit(&audit).await {
            tracing::warn!(tenant_id = %tenant_id, tool = %tool_name, error = %e, "failed to write WASM run audit");
        }
        if success {
            let _ = store.touch_tenant_wasm_tool_last_used(tenant_id, &tool_name).await;
        }

        if success {
            Ok(ToolResult::ok(output))
        } else {
            Ok(ToolResult { success: false, output, error: Some(error.unwrap_or_else(|| "WASM run failed".into())) })
        }
    }
}

struct RegisteredWasmRunResult {
    success: bool,
    output: serde_json::Value,
    elapsed_ms: u64,
    fuel_used: Option<u64>,
}

struct WasmStoreState {
    wasi: WasiP1Ctx,
    limits: wasmtime::StoreLimits,
}

fn execute_registered_module(
    module_bytes: Vec<u8>,
    stdin_data: String,
    args: Vec<String>,
    env_vars: Vec<(String, String)>,
    workspace: Option<String>,
    tool_meta: TenantWasmTool,
    memory_limit_bytes: u64,
    fuel_limit: u64,
) -> anyhow::Result<RegisteredWasmRunResult> {
    let started = Instant::now();

    let mut cfg = Config::new();
    cfg.async_support(false);
    cfg.consume_fuel(true);
    let engine = Engine::new(&cfg)?;

    let stdout_pipe = MemoryOutputPipe::new(MAX_STDOUT_CAPTURE_BYTES);
    let stderr_pipe = MemoryOutputPipe::new(MAX_STDERR_CAPTURE_BYTES);
    let stdout_read = stdout_pipe.clone();
    let stderr_read = stderr_pipe.clone();

    let mut wasi_builder = WasiCtxBuilder::new();
    if !stdin_data.is_empty() {
        wasi_builder.stdin(MemoryInputPipe::new(stdin_data.into_bytes()));
    }
    wasi_builder.stdout(stdout_pipe).stderr(stderr_pipe);
    wasi_builder.args(&args);
    for (key, value) in &env_vars {
        wasi_builder.env(key, value);
    }

    if let Some(workspace_path) = workspace {
        let ws = Path::new(&workspace_path);
        if ws.exists() && (tool_meta.permissions.allow_workspace_read || tool_meta.permissions.allow_workspace_write) {
            let (dir_perms, file_perms) = if tool_meta.permissions.allow_workspace_write {
                (DirPerms::all(), FilePerms::all())
            } else {
                (DirPerms::READ, FilePerms::READ)
            };
            wasi_builder.preopened_dir(ws, "/workspace", dir_perms, file_perms)?;
        }
    }

    let wasm_limits = StoreLimitsBuilder::new()
        .memory_size((memory_limit_bytes.min(usize::MAX as u64)) as usize)
        .instances(1)
        .tables(2)
        .memories(1)
        .build();

    let state = WasmStoreState { wasi: wasi_builder.build_p1(), limits: wasm_limits };
    let mut store = Store::new(&engine, state);
    store.limiter(|state| &mut state.limits);
    store.set_fuel(fuel_limit)?;

    let mut linker: Linker<WasmStoreState> = Linker::new(&engine);
    preview1::add_to_linker_sync(&mut linker, |state| &mut state.wasi)?;

    let module = Module::from_binary(&engine, &module_bytes)?;
    let instance = linker.instantiate(&mut store, &module)?;

    let exit_code: i32 = match instance.get_typed_func::<(), ()>(&mut store, "_start") {
        Ok(func) => match func.call(&mut store, ()) {
            Ok(()) => 0,
            Err(error) => error.downcast_ref::<wasmtime_wasi::I32Exit>().map(|exit| exit.0).unwrap_or(1),
        },
        Err(_) => {
            if let Ok(init) = instance.get_typed_func::<(), ()>(&mut store, "_initialize") {
                init.call(&mut store, ())?;
            }
            0
        }
    };

    let elapsed_ms = started.elapsed().as_millis() as u64;
    let fuel_used = store.get_fuel().ok().map(|remaining| fuel_limit.saturating_sub(remaining));
    let stdout = String::from_utf8_lossy(&stdout_read.try_into_inner().unwrap_or_default()).into_owned();
    let stderr = String::from_utf8_lossy(&stderr_read.try_into_inner().unwrap_or_default()).into_owned();

    let output = serde_json::json!({
        "tool_name": tool_meta.name,
        "tool_version": tool_meta.version,
        "success": exit_code == 0,
        "exit_code": exit_code,
        "stdout": crate::util::truncate(&stdout, 50_000),
        "stderr": crate::util::truncate(&stderr, 10_000),
        "elapsed_ms": elapsed_ms,
        "fuel_used": fuel_used,
        "fuel_limit": fuel_limit,
        "memory_limit_bytes": memory_limit_bytes,
    });

    Ok(RegisteredWasmRunResult { success: exit_code == 0, output, elapsed_ms, fuel_used })
}

fn build_stdin_payload(args: &serde_json::Value) -> String {
    if let Some(stdin) = args["stdin"].as_str() {
        return stdin.to_string();
    }

    if args.get("input").is_some() {
        let input = &args["input"];
        if let Some(s) = input.as_str() {
            s.to_string()
        } else {
            serde_json::to_string(input).unwrap_or_default()
        }
    } else {
        String::new()
    }
}

fn filter_allowed_env(tool: &TenantWasmTool, env_value: &serde_json::Value) -> Vec<(String, String)> {
    if !tool.permissions.allow_env {
        return Vec::new();
    }

    let allow: HashSet<String> = tool.permissions.allowed_env_keys.iter().map(|key| key.to_ascii_lowercase()).collect();
    env_value
        .as_object()
        .map(|values| {
            values
                .iter()
                .filter_map(|(key, value)| {
                    if !allow.contains(&key.to_ascii_lowercase()) {
                        return None;
                    }
                    value.as_str().map(|s| (key.clone(), s.to_string()))
                })
                .collect()
        })
        .unwrap_or_default()
}

}

// Re-exports
pub use wasm_compile::WasmCompileTool;
pub use wasm_exec::WasmExecTool;
pub use wasm_call::WasmCallTool;
pub use wasm_inspect::WasmInspectTool;
pub use run_registered_wasm::RunRegisteredWasmTool;
